services:
  db:
    image: postgres:17.7
    container_name: fastapi_postgres
    environment:
      - POSTGRES_DB=fastapi_db
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_password
    ports:
      - "5432:5432"
